"""empty message

Revision ID: 5a10740622ae
Revises: 
Create Date: 2020-12-13 16:40:19.609686

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5a10740622ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('games_activity',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('game', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('start_datetime', sa.DateTime(), nullable=True),
    sa.Column('stop_datetime', sa.DateTime(), nullable=True),
    sa.Column('duration_in_sec', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games_activity')
    op.drop_table('games')
    # ### end Alembic commands ###
